apiVersion: v1
kind: Secret
metadata:
  name: myapp-secrets
  namespace: myapp
type: Opaque
stringData:
  # Replace with real values (these are plain text for convenience during dev)
  SECRET_KEY: "change-me-in-prod"
  DATABASE_URL: "postgresql://user:pass@postgres:5432/appdb"
