apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: log-time-cronjob
spec:
  schedule: "*/1 * * * *"   # every minute
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          volumes:
            - name: scratch
              emptyDir: {}
            - name: persistent-logs
              persistentVolumeClaim:
                claimName: logs-pvc
          containers:
            # Main: writes to a shared scratch file
            - name: log-time
              image: busybox:latest
              command: ["sh", "-c", "date >> /scratch/time.log"]
              volumeMounts:
                - name: scratch
                  mountPath: /scratch
            # Sidecar: persists scratch log into PVC
            - name: persist-logs
              image: busybox:latest
              command:
                - sh
                - -c
                - |
                  # wait for the main to write, then persist
                  for i in $(seq 1 30); do
                    [ -s /scratch/time.log ] && break
                    sleep 1
                  done
                  # append the run's lines to a durable log
                  touch /mnt/logs/time.log
                  cat /scratch/time.log >> /mnt/logs/time.log
              volumeMounts:
                - name: scratch
                  mountPath: /scratch
                - name: persistent-logs
                  mountPath: /mnt/logs
