apiVersion: apps/v1
kind: Deployment
metadata:
  name: task3-nginx-deployment-with-livenessprobe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task3-nginx-deployment-with-livenessprobe
  template:
    metadata:
      labels:
        app: task3-nginx-deployment-with-livenessprobe
    spec:
      containers:
        - name: task3-nginx-container
          image: nginx:stable
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10