apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: my-app-pdb
spec:
  minAvailable: 2  # Ensure at least 2 pods are available at all times
  selector:
    matchLabels:
      app: my-app
